[2025-02-09T15:10:33.756+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T15:10:33.779+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.wait_for_extract_postgres_and_csv_data manual__2025-02-09T15:09:40.814819+00:00 [queued]>
[2025-02-09T15:10:33.790+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.wait_for_extract_postgres_and_csv_data manual__2025-02-09T15:09:40.814819+00:00 [queued]>
[2025-02-09T15:10:33.792+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-09T15:10:33.811+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_postgres_and_csv_data> on 2025-02-09 15:09:40.814819+00:00
[2025-02-09T15:10:33.820+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1962) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T15:10:33.823+0000] {standard_task_runner.py:72} INFO - Started process 1964 to run task
[2025-02-09T15:10:33.823+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_postgres_and_csv_data', 'wait_for_extract_postgres_and_csv_data', 'manual__2025-02-09T15:09:40.814819+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/Load_CSV_to_Postgres.py', '--cfg-path', '/tmp/tmpog4djenu']
[2025-02-09T15:10:33.826+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask wait_for_extract_postgres_and_csv_data
[2025-02-09T15:10:33.898+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_postgres_and_csv_data.wait_for_extract_postgres_and_csv_data manual__2025-02-09T15:09:40.814819+00:00 [running]> on host 8c410daec8d3
[2025-02-09T15:10:34.252+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_postgres_and_csv_data' AIRFLOW_CTX_TASK_ID='wait_for_extract_postgres_and_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T15:09:40.814819+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T15:09:40.814819+00:00'
[2025-02-09T15:10:34.254+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T15:10:34.254+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T15:10:34.255+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_extract_postgres_and_csv_data state:running start_date:2025-02-09 15:10:33.780263+00:00
[2025-02-09T15:10:34.256+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_and_csv_data and current dag run status:running
[2025-02-09T15:10:34.257+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T15:10:34.258+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-09T15:10:34.259+0000] {external_task.py:258} INFO - Poking for tasks ['next_task'] in dag load_csv_to_postgres on 2025-02-09T15:09:40.814819+00:00 ... 
[2025-02-09T15:10:34.262+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-09T15:11:32.507+0000] {external_task.py:258} INFO - Poking for tasks ['next_task'] in dag load_csv_to_postgres on 2025-02-09T15:09:40.814819+00:00 ... 
[2025-02-09T15:11:35.030+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-02-09T15:11:35.032+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-09T15:11:35.036+0000] {process_utils.py:132} INFO - Sending 15 to group 1964. PIDs of all processes in the group: [1964]
[2025-02-09T15:11:35.037+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1964
[2025-02-09T15:11:35.038+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-09T15:11:35.084+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T15:11:35.133+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1964, status='terminated', exitcode=0, started='15:10:33') (1964) terminated with exit code 0
