[2025-02-09T13:14:25.971+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T13:14:25.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.extract_postgres_data manual__2025-02-09T13:14:21.376741+00:00 [queued]>
[2025-02-09T13:14:26.010+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_postgres_and_csv_data.extract_postgres_data manual__2025-02-09T13:14:21.376741+00:00 [queued]>
[2025-02-09T13:14:26.011+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T13:14:26.032+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_postgres_data> on 2025-02-09 13:14:21.376741+00:00
[2025-02-09T13:14:26.044+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T13:14:26.048+0000] {standard_task_runner.py:72} INFO - Started process 321 to run task
[2025-02-09T13:14:26.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_postgres_and_csv_data', 'extract_postgres_data', 'manual__2025-02-09T13:14:21.376741+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/extract_postgres_and_csv_data.py', '--cfg-path', '/tmp/tmpamjc1o19']
[2025-02-09T13:14:26.049+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask extract_postgres_data
[2025-02-09T13:14:26.137+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_postgres_and_csv_data.extract_postgres_data manual__2025-02-09T13:14:21.376741+00:00 [running]> on host 8c410daec8d3
[2025-02-09T13:14:26.352+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_postgres_and_csv_data' AIRFLOW_CTX_TASK_ID='extract_postgres_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T13:14:21.376741+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T13:14:21.376741+00:00'
[2025-02-09T13:14:26.355+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T13:14:26.355+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T13:14:26.356+0000] {logging_mixin.py:190} INFO - Current task name:extract_postgres_data state:running start_date:2025-02-09 13:14:25.997223+00:00
[2025-02-09T13:14:26.356+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_and_csv_data and current dag run status:running
[2025-02-09T13:14:26.357+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T13:14:26.359+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-09T13:14:26.361+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/meltano/meltano_project/extract/extract_data_db.py']
[2025-02-09T13:14:26.382+0000] {subprocess.py:99} INFO - Output:
[2025-02-09T13:15:52.228+0000] {subprocess.py:106} INFO - Erro ao processar categories: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.230+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.231+0000] {subprocess.py:106} INFO - Erro ao processar products: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.232+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.233+0000] {subprocess.py:106} INFO - Erro ao processar suppliers: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.234+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.235+0000] {subprocess.py:106} INFO - Erro ao processar employees: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.238+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.240+0000] {subprocess.py:106} INFO - Erro ao processar employee_territories: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.241+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.242+0000] {subprocess.py:106} INFO - Erro ao processar territories: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.243+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.244+0000] {subprocess.py:106} INFO - Erro ao processar region: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.245+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.246+0000] {subprocess.py:106} INFO - Erro ao processar orders: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.247+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.248+0000] {subprocess.py:106} INFO - Erro ao processar shippers: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.249+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.249+0000] {subprocess.py:106} INFO - Erro ao processar us_states: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.250+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.251+0000] {subprocess.py:106} INFO - Erro ao processar customer_customer_demo: could not translate host name "db" to address: Temporary failure in name resolution
[2025-02-09T13:15:52.252+0000] {subprocess.py:106} INFO - 
[2025-02-09T13:15:52.253+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-09T13:15:52.349+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T13:15:52.351+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_postgres_and_csv_data, task_id=extract_postgres_data, run_id=manual__2025-02-09T13:14:21.376741+00:00, execution_date=20250209T131421, start_date=20250209T131425, end_date=20250209T131552
[2025-02-09T13:15:52.372+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-09T13:15:52.373+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-09T13:15:52.373+0000] {logging_mixin.py:190} INFO - Dag name:extract_postgres_and_csv_data queued_at:2025-02-09 13:14:21.405827+00:00
[2025-02-09T13:15:52.375+0000] {logging_mixin.py:190} INFO - Task hostname:8c410daec8d3 operator:BashOperator
[2025-02-09T13:15:52.418+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T13:15:52.451+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-09T13:15:52.454+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
